---
title: "末流211考研北航计科学硕430分经验帖"
date: 2021-03-29T23:03:25+08:00
draft: false
---

先说下我的基本情况。我本科是云南大学，六级一年没学英语，裸考485；四级考前做了几张卷子，602. 在大学专业课和绩点都一般，数学可能稍微好些，基本就是平时自己做下作业，考前突击下，能考九十多（考的很水。。）。
考研成绩是政治74，英语80，数学138，专业课138.
我正式准备考研是从5月中旬开始，每天早上3小时数学，下午2-3小时专业课，晚上2小时数学习题；每周休息半天，差不多这个节奏一直到考前。英语和政治没有专门划时间，夹在休息时间里学。还有就是虽然安排是每周休息半天，其实中间可能有几天也在划水没学习。。

* 初试
** 政治
   政治可以准备的晚一些。但我比较怂，从7月就开始每天晚上看一集徐涛的课，看一章后做一章的1000题。本来还买了精讲精练，却没怎么翻过。。后面又买了徐涛的小黄书想看看有什么不一样的，还可以跟着课在书上划。但是划了几天后感觉这样反而会降低上课的专注度，不如自己做笔记，或者如果懒得做就直接听，都比为了找书上对应的地方经常跟不上课程节奏要好得多。而且小黄书编的我感觉确实不如精讲精练，没有突出重点，只是一个接一个列知识点。说句题外话，我感觉马原中的“实事求是”确实非常适合考研。如果你是一个坚定的唯物主义者，就不会寄希望于考试刚好考到你会的知识点，也能认清自己和大神的差距，不会幻想不用努力知识就直接跑进脑子之类的奇迹。看到自己和别人的进度差距后要做的是脚踏实地，一步一步慢慢走，一点一点慢慢啃书。囫囵吞枣带来的心理安慰没有一点用。在书上划线和做一大堆笔记也只是起到心理安慰的作用，要做的笔记不是好看的笔记，是方便自己复习的笔记。上课不是为了划线，是为了听懂。因此光顾着划线却没仔细听讲，不如啥都不干就坐着听课的效果来的好。关于作息也是一样，早上一大早起床导致一上午昏昏欲睡不如睡到自然醒。整天泡图书馆有时候反倒不如中间去操场玩几个小时。只有自己知道今天到底有没有真正用功，表面上谁都看不出来。说回正题，在8月我找到了一个题库小程序小白政治，每天午饭后在上面刷一节。这样一直到10月终于把1000题刷完了。。我花了两个晚上理了一下时间线和知识点后就没二刷，开始看腿姐的技巧课。每天也听腿姐在喜马拉雅的带背，买了她的背诵手册早上抽点时间背后面的知识清单。还买了肖秀荣的几本小册子，但没看。。肖六出了后做了上面的选择题。在记乎上买了一份各种政治模拟卷选择题合集，每天几十道反复刷。我感觉这时刷的选择题应该是对我提分起的作用最大的。第一遍做1000题和小白的时候正确率一般在50%左右，可能高些。。做肖六平均有35吧，后面的肖四也差不多。。肖四出了后先做了选择题。最后2周才开始准备政治的主观题。肖四一共20道大题，每天背2道背到考前。考前几天做了唯一一次模拟（也是唯一一次写主观题），感觉对把握时间还是很有帮助的。
** 英语
   我从年后就开始用app背英语单词，一直背到考前。中间虽然换过几个app（从百词斩换到默默，到扇贝，最后到欧陆），但app上还是一直在背的。4月开始买了恋恋有词按记忆曲线背list。6月开始每天中午午休抽点时间做两篇阅读，到9月把05年到20年共15年的阅读做了2遍。05年再往前的做过一张，感觉题型有点不一样（错的很多。。）就没做了。我第一遍做阅读大概一张卷子错3-4个吧，第二遍可能2-3个。。9月开始做完型和新题型，10月开始练作文和套卷。因为阅读已经是第三遍了，答案可能很多都能背下来了，就基本没多少错。我开始练作文时先大致翻了潘赟的作文书（不推荐买实体书，感觉内容有点虚，pdf完全够用），在margin note上把书里的内容整理成思维导图，熟悉了作文大致的框架（考研作文感觉蛮八股的，都是一个套路），然后每周练2-3篇，自己写完后看范文结构，整理一些句子。到最后一共练了十几篇作文。11月在网上找了一些关于作文的帖子，背了一个万能的结尾段，前两段靠积累的结构和句子到考场临场发挥。
   总结一下我英语就是一直背单词，背了至少5-6轮；做了3遍近15年阅读；整理了一下作文结构。
** 数学
   虽然4月就看到群里好多人数学进度已经甩老远了，也一直蛮焦虑的，我正式开始准备却一直拖到了5月中旬。开始的时候看到李永乐的线代视频课，本来想试试水，结果看着感觉还行就直接跟着从线代开始了。花了一周看完了20年的线代强化课视频，在他的辅导讲义上做了好多笔记。然后开始啃李正元全书。每天早上3小时用来看全书，晚上做对应的1800高数基础题，这样一直到8月前差不多结束一轮。很多时候晚上做题的进度跟不上早上看全书的进度（我一般每天只能啃10页，把每道例题都做一遍），就直接跳过了那个章节还没做完的题，和上午的进度同步。
   第一轮啃全书的时候感觉有些地方说的可能不是很全，就买了本张宇18讲想看看有没有补充，结果发现基本上知识点是差不多的。。既然买了18讲，第二轮就顺便用它了。7月开始第二轮，早上3小时用来看张宇18讲的网课，晚上做对应的题，花了一个半月刷完了。做了后我感觉不是很推荐张宇，他出的题和书里总结的解法有些感觉很怪，真正考研不会用上（凭我后来刷的15年真题和实际考试感受得到），对比李正元的书总结的就很舒服。第二轮做完高数后线代和概率一起上，上午做余炳森的概率（群里推荐的，书确实整理的蛮好），晚上做李永乐的线代辅导讲义（第一遍的时候还有好多题没做，而且这时前面只花了一周学的线代知识已经忘的差不多了）。周末会做660。今年的660还是比较简单的，特别是线代和概率部分，因此做660总共花的时间并不多。第二轮差不多在9月中旬完成。这时看到李林的书便宜就下单买了（三本讲义一共9.9包邮），翻了下发现里面高数讲中值定理和泰勒公式比较详细，刚好可以弥补李正元全书的不足。就花了2周把那两章做了一遍，整理后感觉确实收获颇丰。做660的时候开始整理错题到错题本上。我感觉第一轮完全不需要错题本，到第二、三轮错题本可能才能发挥上用场。每周会花半天到2天的时间来做错题本，每次上面做的题会做个熟练度标记，下次把熟练度低的题重新做一遍。经常会有做过几遍还是不会做的题，可能这就是没什么天赋的人的日常吧。。。
   二轮结束后感觉做题还是不太行，网上下了李林880做了一些感觉出的确实不错，就买了实体书。这时我看网上别人已经真题都刷到第二遍了，我却还没碰过真题。。但按照自己的节奏来确实还是蛮有必要的。事实证明，到最后开始刷真题的时候我虽然只刷了一遍，但感觉完全没必要刷第二遍，而且时间充裕的后期甚至不知道做什么。。李林880题量还是有点大，这之后全部做不太现实。好在李林在微博和公众号上给划了重点题，我就只做了他划的那些题。9月中到10月底我数学安排是早上做880重点题，晚上做108题。中间花了2周早上改做李林高数讲义里的中值定理。这时每周开始把周日拿出来做真题，早上3小时做一张数学，下午一张961，晚上来对答案整理后继续做108.
   11月开始每天刷真题。这时感觉任务反倒减轻了，早上一张卷子一般2个小时多能做完。真题做到头基本没有不会的题目，但是每次都因为粗心扣个十几分，只有两三次能拿满分。李林6套出了后渐渐的真题差不多做完了15年，开始做模拟题。模拟题做了李林的6+4和合工大的共创5套。感觉做着比真题要卡些，但也还行。后面有的时候会感觉没什么试卷好做，但还是得每两天刷一张数学卷子来保持手感，否则容易忘知识点。试卷不是用来打分的，是用来查漏补缺的。就是把考研的知识点全覆盖，你做完看看还有没有没掌握的，要是有就可以去那些地方专门强化。为了多刷点卷子巩固知识点，刷完15年真题和几张模拟题后我怕剩下的卷子数量撑不到考试（李林和合工大是网上一致评价质量好的卷子，质量差的卷子我感觉不接近真题刷了也没用），我试着做了几张05年之前的老真题，但感觉太简单了，根本没必要。。
** 专业课961
   专业课我也是从5月中旬正式开始的。5月到7月每天下午两个多小时做王道，看一章做一章题，答案不直接写到书上。顺序是计组-操作系统-计网。计组中间对应的汇编指令和CPU两章啃黑书，但王道的题最好也还是做做，我后面在961真题上找到过王道在那两章里的题。8月差不多到2轮。2轮就只大致看了每章内容，做了选择题，还是没把答案写书上，但标记了错题。中间花了2周做了黑书上的习题（做那个真的花时间。。），对理解还是起到很大作用的。我看很多学长学姐说MIPS CPU的几张图要背下来，但我记忆力不好，背不下来。。后面做真题发现还是理解更重要些，961真题一般不会直接给书上一模一样的结构，会在一些旁路上做些手脚，让你自己分析有什么影响。二轮的顺序是先计组和操作系统隔天轮换，两门看完后看计网。9月底开始3轮。第三轮主要是理清每章的知识结构，自己整理一份导图（我发现自己画一幅比看别人整理的要有用的多），最好能给别人讲解三门课教了什么。每章王道都细看一遍，课后题只看前面标记的错题，大致看下大题。这次是每3天3门课轮换。在2轮和3轮之间我花了一周做了961真题的选填（一共就5张），提前了解下真题。3轮还看了北航的课件。结束差不多是10月中旬，王道买的408真题和模拟题刚好发货。开始第4轮，一天做408卷子一天做王道课后题。这次直接写到书上了，而且没怎么看前面的知识点，要看也是看自己整理的导图，所以很快就写完了。而且这是第4轮了，差不多题目也都背下来了。。。这遍应该是在快12月的时候结束。后面试着做了几张王道的模拟题，出的那叫一个一言难尽，屎一样！去刷刷选择题还行。至于大题，别看。12月以后就是做961真题了。计划是每2天一张，但因为中间摸了好多鱼，拖到考前一周刚好做到最后一张用来模拟。
* 复试
** 机试
   我的机试是用CSP 320分，2.8%抵的。其实我是考了CSP后看到北航能换分才考虑考北航的2333. 我觉得要是有机会去考，考了换分应该是很划算的，可以在准备复试的时候减轻很多心理压力。前两题200分就是送的，而直接拿200分去换也不会亏（大佬除外）。还有就是先考一次这个能让自己有考北航的信心。如果准备了后还考不到200就算进了复试机试也很容易被刷。我没有为这个考试特别准备过，考了两次都是直接上的。第二次是考研的9月，半年没写代码了直接上考了300. 第三题细心点，别着急慢慢写就行。可能是因为我的面试比较差，初试第5，复试后总分第7.
** 面试
   考完后完全没什么心情准备面试，还去实习了。出分前更是一点底都没有，甚至不知道自己能不能进复试（我自己估分最低是280。。），就在每天上班前看一会离散。后面开始每天写博客整理可能会被问到的课程和项目。结果准备的课基本都没问，问了几个很基础的问题。我们是网上面试，一进去先让抽一道政治。然后是英语自我介绍。说完后老师用英语问我最常用的编程语言是什么，我说cpp。然后问有什么难点，我说了一些面向对象的特性比较难记忆和理解。英语完了后是线性代数，问我怎么解线性方程组Ax=b，还有怎么判断一个向量组无关。之后是离散，问了偏序，全序，良序是什么。然后是数据结构，问给一个文本，怎么统计每个词的词频。我说python可以用字典，C++可以用Map，老师说他问实现的数据结构是什么，我说红黑树。老师继续问我红黑树的细节是怎样的。。我答不上来，就说了还可以用二叉排序树，用字典序进行排序，找到后给节点的记数+1，找不到就新建节点。老师问复杂度是多少，我说对数复杂度。然后老师还问我知不知道多态是什么，我说了一大堆，后来想想应该是答错了。。最后问了我有什么项目，我说了一半时间就到了。
* 后话
  我的考研经历大致就是这些了，希望对你们有点用吧。中间我省了很多废话，要是对一些更详细的细节感兴趣的话可以看下[[https://iluvata.github.io/post/2021-02-16_yearly-review/][我的博客]]，里面更详细的记录了一些我的学习方法啥的，虽然更多的是废话哈哈.总结起来我感觉我自己的考研之路还是相对比较轻松的，特别是后期疯狂摸鱼，又是跑步又是看小说，考前两周还因为在大冷天跑步后冲凉把自己送进了医院。。。考完后我自己的估分是280-400，出分的时候突然跳出来430我着实是吓了一跳，看来改卷并没有我想象的那么严格2333.最后祝大家都能考上自己喜欢的研究生，欢迎到然姐的北航考研群473862594，或直接找我1124026683问问题。
